name: Self-Hosted CI with Local Docker & Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure Docker is available
      - name: Docker version
        run: docker --version

      # Step 3: Build local Docker image
      - name: Build Docker image
        run: docker build -t wisecow:local .

      # Step 4: Test Docker image locally
      - name: Test Docker image
        run: |
          docker run -d --name wisecow-test -p 4499:4499 wisecow:local
          echo "Waiting for container to start..."
          sleep 10
          echo "Checking health endpoint..."
          curl -v http://localhost:4499 || true
          docker stop wisecow-test
          docker rm wisecow-test

      # Step 5: Apply Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
          kubectl apply -f wisecow-ingress.yaml

      # Step 6: Get pods, services, ingress (simplified)
      - name: List Kubernetes resources
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress

      # Step 7: Validate deployment with curl
      - name: Validate deployment with curl
        run: |
          echo "Waiting 10 seconds for service to stabilize..."
          sleep 10
          NODE_PORT=$(kubectl get svc wisecow-service -o jsonpath='{.spec.ports[0].nodePort}')
          echo "NodePort is $NODE_PORT"
          curl -v http://localhost:$NODE_PORT || true
